name: "Terraform Dev"

on:
  pull_request:
    branches:
      - master
    paths:
      - 'dev/**'
    types: [opened, synchronize, closed, labeled]

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        if: ((github.event.action == 'labeled') && (github.event.label.name == 'plan:dev'))
        id: plan
        run: terraform plan

      - name: Terraform Apply
        if: ((github.event.action == 'labeled') && (github.event.label.name == 'apply:dev'))
        id: apply
        run: terraform apply
